apiVersion: v1
kind: Pod
metadata:
  name: environment

spec:
  containers:
    - name: nginx
      image: nginx
      env:
        - name: course
          value: devops
        - name: trainer
          value: siva kumar reddy
        - name: duration
          value: "120hrs"