apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels: # these labels are replicaset labels
    app: nginx
    tier: frontend
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
    # these are used to select the pod to create replicas
      tier: frontend
      app: nginx
    # this is pod defination
  template:
    metadata:
    # these labels belong to pod
      labels:
        tier: frontend
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
    tier: frontend
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: 80
    targetPort: 80
